### PR TITLE
Support SourceIRC Logging

### PR DESCRIPTION
**Pull request by vintagepc**
Simple modification to reflect log messages to a [SourceIRC](https://github.com/Azelphur/SourceIRC) channel flagged with "lilac" in the SourceIRC config.

### CODE REVIEW

**Comment by J-Tanzanite** [comment]
One of the things I am concerned about is calling any of the `IRC_*` functions without using `#if defined *`

Like here: 
```
PrintToServer("SourceIRC:");
PrintToServer("\tNative Exists: %s", ((NATIVE_EXISTS("IRC_MsgFlaggedChannels")) ? "Yes" : "No"));
if (NATIVE_EXISTS("IRC_MsgFlaggedChannels")) {
	IRC_MsgFlaggedChannels("lilac", "[LILAC] is active and logging to SourceIRC!");
}
```

`#tryinclude <*>`
Will try to include a file, but if it fails, it won't error out. That's all it does.
However, if a file isn't included, then any calls to the failed included file's functions will cause an error... Because, well, it failed to include the functions, so it doesn't know what any of the `IRC_*` stuff is.

You can see Lilac checking if SourceBans++ was successfully included before trying to use any of its methods here: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/45160447b189a8fc4e679003869674b639090242/scripting/lilac/lilac_stock.sp#L225

To fix this, I suggest doing something like this:
```
PrintToServer("SourceIRC:");
PrintToServer("\tNative Exists: %s", ((NATIVE_EXISTS("IRC_MsgFlaggedChannels")) ? "Yes" : "No"));
#if defined ...
```
...
...

I went to check what the SourceIRC include guard is...
But...
## It doesn't have one?!
I can't find it, am I blind? https://github.com/Azelphur/SourceIRC/blob/master/scripting/include/sourceirc.inc

Ok, so... Here's what I mean.
In SourceBans++, there is a include guard: https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/include/sourcebanspp.inc#L27

And this means that sourcebans++ can't be included twice.
This is REALLY needed to prevent double includes.
But in this project, it's required to prevent issues where tryinclude fails.

See, without this, people have to download SourceIRC in order to compile Lilac, even if they don't plan on using SourceIRC... This is not acceptable.
Lets take Material-Admin as an example.
MA is a Russian Fork of SB++, because of this, as you can imagine, most people using this will be Russians.
It's completely unreasonable to force most people (who aren't Russians) to get the MaterialAdmin include file _just_ so they can compile Lilac.

...

I was going to bring up the need for a `lilac_sourceirc` ConVar, as there should be a ConVar so it can be easily toggled off... But... With this tryinclude issue - We might have to ask the SourceIRC people to first make an include guard, before SourceIRC can even be added to Lilac...
...

However, I think even this might cause issues.
Because there wasn't an include guard before, that means that SourceIRC won't work for a lot of people.
People might have an older version of SourceIRC installed, and because the define isn't in the older versions - actually adding SourceIRC support might not work for a lot of people unless they update their SourceIRC include file first?

This is a problem...
Unless I am stupid and there is an easy fix... I hope there is at least...

**Comment by vintagepc** [comment]
Whoops, I didn't do a complete implementation. It's possible to forward-declare the SourceIRC native (since it's a single call we need to access). This means it's possible to compile without the SourceIRC include and still get functionality.

**Comment by J-Tanzanite** [comment]
Sourcemod has forward declaration? I thought it didn't...
Well done, day saved :D

Anyway, as I mentioned earlier, it would be nice to have a ConVar for SourceIRC, something like `lilac_sourceirc`.
Not sure if it needs more than a simple "on / off". By the looks of it (a glance) a simple on / off is enough.

**Comment by vintagepc** [comment]
Ah, just saw this after I filed the new PR. I'll add the convar. :+1:

**Comment by vintagepc** [comment]
BTW - do you have a private way I can reach you? have a topic or two I'd like to discuss out-of-band.

**Comment by J-Tanzanite** [comment]
> BTW - do you have a private way I can reach you? have a lilac-related topic or two I'd like to discuss out-of-band.

The most reliable place you can contact me is on steam: https://steamcommunity.com/id/J_Tanzanite
(Ignore the Stalin theme, it's a meme)

I'm still moving btw, so I'll be slow to reply, and deal with the PRs atm. :/

**Comment by vintagepc** [comment]
No worries, life comes first :+1:

**Comment by J-Tanzanite** [comment]
Closing due to new PR

**Comment by vintagepc** [comment]
Great - sent you a steam invite. :+1:

**Pull request closed without merging**
