### PR TITLE
Update lilac_globals.sp

### PR DESCRIPTION
**Pull request by Gr1Z**
Я проверял работает не плохо на CSS v34

### CODE REVIEW

**Comment by J-Tanzanite** [comment]
Sadly, just changing the values would impact other games...
And since CSS v34 doesn't normalize angles correctly, I would doubt that even this patch would be stable in all cases...
...
Besides, I don't support CSS v34 or v91...

---

That said, with people frequently asking for support... Maybe I should at least check if I could add some code to detect CSS v34, and disable angle checks all together...

Not sure how I would go about doing so, but there should be a way?

**Comment by Gr1Z** [comment]
> Sadly, just changing the values would impact other games... And since CSS v34 doesn't normalize angles correctly, I would doubt that even this patch would be stable in all cases... ... Besides, I don't support CSS v34 or v91...
> 
> That said, with people frequently asking for support... Maybe I should at least check if I could add some code to detect CSS v34, and disable angle checks all together...
> 
> Not sure how I would go about doing so, but there should be a way?

Напиши попробуй ему Kailo#8984

**Comment by J-Tanzanite** [comment]
Sorry for having been gone for so long, a lot has happened.

Anyway, sadly, I cannot take this patch.
This patch would add support for a cracked/non-steam version of a game (which isn't supported) but it would do so at the detriment of other Source games; making Angle Cheat detections worse.

One thing I might want to look more into, is auto detection of old versions of CS:S, and then apply this patch.
I have tried to figure out how to do this, but I still haven't figured it out.
So sadly, this PR will be closed for the time being.

I still don't support using cracked versions of games, but since CS:S is old, and support is highly requested, *will* look further into this, and hopefully get at least this issue solved.

**Comment by khabib227** [comment]
@J-Tanzanite and if you query a setting present just on CSS v34? For instance cl_min_ct. If the setting is present so is v34? CSGO don't has this setting right?

**Pull request closed without merging**
