### PR TITLE
Translations changes

### PR DESCRIPTION
**Pull request by Tiagoquix**
Changes:

- Added the new strings to the Brazilian Portuguese translation.
- Changed some things on the original translation.

### CODE REVIEW

**Comment by J-Tanzanite** [comment]
There are a few problems with this PR.

I'm not a fan of the uppercase to lowercase changes, but that's preference and style, which isn't a big deal.
But the punctuation is a problem.

For the welcome message, it's a little weird having another punctuation, considering the version number has those in it.
`This server is protected by Little Anti-Cheat 1.6.3.`
I prefer to have none there.

When it comes to kick messages on the other hand, that's a big problem; because punctuation is automatically appended at the end by Sourcemod (Source: https://sm.alliedmods.net/new-api/clients/KickClient).
The same applies to bans.

Indent change is fine however.

---

When it comes to the PT changes tho, there is a bit of a PR conflict issue.
See, the translations in the master branch aren't the same as the ones in the restructured branch.
There's been a lot of mixing here, and that's something I have to sort out before I can take your PR.

Then there is also this: https://github.com/J-Tanzanite/Little-Anti-Cheat/pull/64
Currently I'm waiting to get that PR, then I'll fix the translations to be uniform across all the versions and then more changes can be applied.

Sorry for the mess :(

**Comment by J-Tanzanite** [comment]
Alright, I finally got around to fixing the translation mess...
Basically, the translations weren't the same across the master branch (official version) and the restructured branch (new upcoming version).

Because of this, accepting translations has been... Annoying. It's finally sorted out.
But, this fix did cause some conflicts in this PR.

Sorry about that, kinda inevitable tho, since you and someone else wanted to update the same translation files at the same time.
If you could re-do the PR or fix the merge conflicts, I could finally look into accepting your PR.

Again, sorry for the mess. :(

**Comment by Tiagoquix** [comment]
@J-Tanzanite Can you give me an example of what the `{1}` is on the `kick_macro` phrase?

```
	"kick_macro"
	{
		"#format"	"{1:s}"
		"en"		"{1} Macro is not allowed on this server"
	}
```

**Comment by J-Tanzanite** [comment]
Currently there are two options: `Auto-Jump` and `Auto-Shoot`.
However, I wrote the code in such a way that it would be easy to add another option, should one be needed in the future.

**Comment by Tiagoquix** [comment]
> Currently there are two options: `Auto-Jump` and `Auto-Shoot`.
> However, I wrote the code in such a way that it would be easy to add another option, should one be needed in the future.

All right. Thanks. I did need the example to better adapt the PT-BR translation.

**Comment by Tiagoquix** [comment]
Done @J-Tanzanite.

I have a question. Is it a problem to have a dot on the "message blocked" phrases?
If no, you can merge without any problems. If yes, let me know and I will remove the dots.

**Comment by J-Tanzanite** [comment]
Having a dot on the message blocked isn't a problem, only for kick and bans :)

Anyway, the changes seem fine, the English improvements are neat too.
Thanks, and merged :)

**Pull request merged**
